# Generated by Django 4.0.6 on 2022-07-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='asdfgf', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
